name: build-and-deploy
run-name: Build and Deploy to GitHub Pages ğŸš€
on: [ push ]
branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Job was triggered"
      - run: echo "ğŸ§ Running on ${{ runner.os }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
